#include "client.h"
#include "UI.h"

#include <chrono>
#include <thread>

namespace {

void clientLoop(Client& client, UI& ui)
{
    bool running = true;

    while (running) {
        /*
         * Process everything currently waiting in the UI -> Client queue.
         */
        ClientRequest request;

        while (running && ui.tryGetRequest(request)) {
            switch (request.type) {
            case ClientRequest::Type::Login: {
                bool success = client.login(request.username);

                UIEvent event;
                event.type = UIEvent::Type::LoginResult;
                event.username = request.username;
                event.success = success;

                ui.pushEvent(std::move(event));
                break;
            }

            case ClientRequest::Type::SendMessage: {
                MessageId id = client.send(request.message);

                /*
                 * The client has accepted the message for transmission.
                 *
                 * The eventual NACK, if any, will be generated by
                 * Client::poll() and sent to the UI asynchronously.
                 */
                (void)id;
                break;
            }

            case ClientRequest::Type::GetUsers: {
                auto users = client.getUsers();

                UIEvent event;
                event.type = UIEvent::Type::UsersReceived;
                event.users = std::move(users);

                ui.pushEvent(std::move(event));
                break;
            }

            case ClientRequest::Type::Quit:
                client.quit();
                running = false;
                break;
            }
        }

        if (!running)
            break;

        /*
         * Check the socket for incoming packets.
         *
         * Client::poll() should generate UI events through ui.pushEvent().
         *
         * For example:
         *
         *   MESSAGE -> MessageReceived
         *   NACK    -> MessageNacked
         *   ...
         */
        client.poll();

        /*
         * Don't busy-spin if there is currently nothing to do.
         *
         * Ideally Client::poll() itself should block for a short amount
         * of time, or the UI/request queue should provide a wakeup
         * mechanism. This is just a simple starting point.
         */
        std::this_thread::sleep_for(std::chrono::milliseconds(5));
    }

    ui.stop();
}

} // namespace

int main()
{
    UI ui;
    Client client;

    /*
     * The UI owns the terminal and runs on its own thread.
     */
    ui.start();

    /*
     * The Client owns the socket and runs entirely on this thread.
     */
    std::thread clientThread([&] {
        clientLoop(client, ui);
    });

    /*
     * Wait for the client thread to finish.
     *
     * The UI thread is managed internally by UI::start()/UI::stop().
     */
    clientThread.join();

    /*
     * Make sure the UI has finished before exiting.
     */
    ui.stop();

    return 0;
}
